### ISSUE TITLE
Serious Sam Classic Patch Entity Point Not Found

### ISSUE THREAD

**Issue by cubabori** [SamClassicPatch/GameExecutable#4]
So I created my own bin folder as it supposedly can work out of and I get this error. Even if I install it via the vanilla bin folder.
![Screenshot 2024-12-05 170953](https://github.com/user-attachments/assets/4dc6acec-243c-4258-85c5-1accbe04101e)

**Comment by DreamyCecil** [comment]
Make sure that you've installed the correct version of the patch. It seems like you're trying to apply a patch for **TSE 1.07** on **TFE 1.05**.

**Comment by cubabori** [comment]
Thanks alot. Though I wonder if there's a way to fix cutscene FOVs for ultrawide resolutions.

**Comment by DreamyCecil** [comment]
"Fix field of view" option (`sam_bUseVerticalFOV` command) has two states:
1. Fix for all projections (`sam_bUseVerticalFOV = 1`)
2. Fix only for player view (`sam_bUseVerticalFOV = 2`)

If you want to fix the FOV in cameras, use the first option. Though I've been told that some maps look off with it, that's why the second option exists and is set by default.
